name: Test

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.9.2"]
    steps:
    - name: Install swiftly
      run: curl -L https://swift-server.github.io/swiftly/swiftly-install.sh | bash
    - name: Install Swift
      run: swiftly install ${{ matrix.swift }}
    - uses: actions/checkout@v4
    - name: Generate dotenv
      run: |
        touch .env
        echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> .env
        echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
        echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
        echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> .env
    - name: Build
      run: swift build -v
    - name: Test Swift
      run: swift test
